### PR TITLE
add USDC + refactor

### PR DESCRIPTION
**Pull request by aaronmgdr**
adds USDC 

make it so many erc20s on eth can be added without needing to create many functions

### CODE REVIEW

**Review by carterqw2 — APPROVED** [review]
Looks good.

**Comment by bayological** [comment]
@aaronmgdr When running locally I don't see the USDC balance. Also there isn't a token colour assigned to USDC in PieChart.tsx.

image

**Review by bayological — CHANGES_REQUESTED** [review]
@aaronmgdr When running this locally the USDC balance isn't showing. Also there isn't a colour assigned to USDC for the pie chart.

image

**Comment by aaronmgdr** [comment]
closing since ive learned this repo is not the right one

https://github.com/mento-protocol/reserve-site/pull/3

**Pull request closed without merging**
